<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend><br>
        <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>



        <?php //echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("ApexDivision_CustomerAttribute::additional_gstin.phtml")->toHtml(); ?>

        <div class="field tjuk_gstin">
            <label class="label" for="tjuk_gstin"><span><?php /* @escapeNotVerified */ echo __('GSTIN'); ?></span></label>
            <div class="control">
		<input type="text" id="tjuk_gstin" name="tjuk_gstin" value="<?php if($t_var = $block->getCustomer()->getCustomAttribute('tjuk_gstin')) { echo $t_var->getValue(); } ?>" title="<?php /* @escapeNotVerified */ echo __('GSTIN') ?>" class="input-text" autocomplete="off" />
            </div>
        </div>


        <div class="field tjuk_fssai">
            <label class="label" for="tjuk_fssai"><span><?php /* @escapeNotVerified */ echo __('FSSAI'); ?></span></label>
            <div class="control">
		<input type="text" id="tjuk_fssai" name="tjuk_fssai" value="<?php if($t_var = $block->getCustomer()->getCustomAttribute('tjuk_fssai')) { echo $t_var->getValue(); } ?>" title="<?php /* @escapeNotVerified */ echo __('FSSAI') ?>" class="input-text" autocomplete="off" />
            </div>
        </div>


        <div class="field tjuk_customer_company_name">
            <label class="label" for="tjuk_customer_company_name"><span><?php /* @escapeNotVerified */ echo __('Company Name'); ?></span></label>
            <div class="control">
                <input type="text" id="tjuk_customer_company_name" name="tjuk_customer_company_name" value="<?php if($t_var = $block->getCustomer()->getCustomAttribute('tjuk_customer_company_name')) { echo $t_var->getValue(); } ?>" title="<?php /* @escapeNotVerified */ echo __('Company Name') ?>" class="input-text" autocomplete="off"/>
            </div>
        </div>


        <div class="field tjuk_business_role">
            <label class="label" for="tjuk_business_role"><span><?php /* @escapeNotVerified */ echo __('Role') ?></span></label>
            <select id="tjuk_business_role" name="tjuk_business_role" title="<?php /* @escapeNotVerified */ echo __('Role') ?>" class="tjuk_business_role">
                <option value="None"><?= $block->escapeHtml(__('Please select a role.')) ?></option>
                <option value="Purchase Head"<?php if($block->getCustomer()->getCustomAttribute('tjuk_business_role')->getValue() == "Purchase Head") { echo " selected"; } ?>>Purchase Head</option>
                <option value="Purchase Manager"<?php if($block->getCustomer()->getCustomAttribute('tjuk_business_role')->getValue() == "Purchase Manager") { echo " selected"; } ?>>Purchase Manager</option>
                <option value="Purchase Executive"<?php if($block->getCustomer()->getCustomAttribute('tjuk_business_role')->getValue() == "Purchase Executive") { echo " selected"; } ?>>Purchase Executive</option>
                <option value="F&B Head"<?php if($block->getCustomer()->getCustomAttribute('tjuk_business_role')->getValue() == "F&B Head") { echo " selected"; } ?>>F&B Head</option>
                <option value="F&B Manager"<?php if($block->getCustomer()->getCustomAttribute('tjuk_business_role')->getValue() == "F&B Manager") { echo " selected"; } ?>>F&B Manager</option>
                <option value="Other"<?php if($block->getCustomer()->getCustomAttribute('tjuk_business_role')->getValue() == "Other") { echo " selected"; } ?>>Other</option>
            </select>
        </div>


        <div class="field tjuk_customer_code">
            <label class="label" for="tjuk_customer_code"><span><?php /* @escapeNotVerified */ echo __('Customer Code'); ?></span></label>
            <div class="control">
                <input type="text" id="tjuk_customer_code" name="tjuk_customer_code" value="<?php if($t_var = $block->getCustomer()->getCustomAttribute('tjuk_customer_code')) { echo $t_var->getValue(); } ?>" title="<?php /* @escapeNotVerified */ echo __('Customer Code') ?>" class="input-text" autocomplete="off" readonly/>
            </div>
        </div>


        <div class="field tjuk_customer_website">
            <label class="label" for="tjuk_customer_website"><span><?php /* @escapeNotVerified */ echo __('Website'); ?></span></label>
            <div class="control">
                <input type="text" id="tjuk_customer_website" name="tjuk_customer_website" value="<?php if($t_var = $block->getCustomer()->getCustomAttribute('tjuk_customer_website')) { echo $t_var->getValue(); } ?>" title="<?php /* @escapeNotVerified */ echo __('Website') ?>" class="input-text" autocomplete="off"/>
            </div>
        </div>


        <div class="field tjuk_customer_special_margin">
            <label class="label" for="tjuk_customer_special_margin"><span><?php /* @escapeNotVerified */ echo __('Special Margin'); ?></span></label>
            <div class="control">
                <input type="text" id="tjuk_customer_special_margin" name="tjuk_customer_special_margin" value="<?php if($t_var = $block->getCustomer()->getCustomAttribute('tjuk_customer_special_margin')) { echo $t_var->getValue(); } ?>" title="<?php /* @escapeNotVerified */ echo __('Special Margin') ?>" class="input-text" autocomplete="off" readonly/>
            </div>
        </div>


        <div class="field tjuk_customer_available_credit">
            <label class="label" for="tjuk_customer_available_credit"><span><?php /* @escapeNotVerified */ echo __('Available Credit'); ?></span></label>
            <div class="control">
                <input type="text" id="tjuk_customer_available_credit" name="tjuk_customer_available_credit" value="<?php if($t_var = $block->getCustomer()->getCustomAttribute('tjuk_customer_available_credit')) { echo $t_var->getValue(); } ?>" title="<?php /* @escapeNotVerified */ echo __('Available Credit') ?>" class="input-text" autocomplete="off" readonly/>
            </div>
        </div>



        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_dob->isEnabled()) : ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()) : ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()) : ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) : ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>
    </fieldset>

    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
    </fieldset>
    <?= $block->getChildHtml('form_additional_info') ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()) : ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else : ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
