<fieldset class="fieldset create">
    <legend class="legend"><span>Affiliate</span></legend>
    <br>
    <div class="field affiliate_code">
        <label class="label" for="refer_code">
            <span><?= $block->escapeHtml(__('Refer Code')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="refer_code" id="refer_code" value=""
                   title="<?= $block->escapeHtmlAttr(__('Refer Code')) ?>" class="input-text">
        </div>
    </div>
</fieldset>