<?php

use Webkul\AddProductlogo\Block\DIsplay;

?>

<h2 style="text-align: center;">Product Logo</h2>

<a class="action primary" style="margin-left: 85%;" href="<?php echo $block->getUrl('addproductlogo/index/index'); ?>">Add Product Logo</a>

<table>
     <tr>
          <th>Id</th>
          <th>Logo 1</th>
          <th>Logo 2</th>
          <th>Logo 3</th>
          <th>Logo 4</th>
          <th>Logo 5</th>
          <th>Created At</th>
          <!-- <th>Updated At</th> -->
          <th colspan="2">Action</th>
     </tr>
 
     <?php
          
          $collection = $block->getResult();
          foreach($collection as $item){
               $image_path = $block->getUrl("pub/media/productlogo/");
          	$image = $item->getData('featured_image');
               $final_path = $image_path.$image;

               $image_one = $item->getData('featured_image_one');
               $final_path_one = $image_path.$image_one;

               $image_two = $item->getData('featured_image_two');
               $final_path_two = $image_path.$image_two;

               $image_three = $item->getData('featured_image_three');
               $final_path_three = $image_path.$image_three;

               $image_four = $item->getData('featured_image_four');
               $final_path_four = $image_path.$image_four;
     		
     		
     ?>
     <tr>
          <td><?php echo $item->getData('post_id'); ?></td>
          <td>
          	<img src="<?php echo $final_path; ?>" height="50" width="100" Alt="No image" />
          </td>
          <td>
               <img src="<?php echo $final_path_one; ?>" height="50" width="100" Alt="No image" />
          </td>
          <td>
               <img src="<?php echo $final_path_two; ?>" height="50" width="100" Alt="No image" />
          </td>
          <td>
               <img src="<?php echo $final_path_three; ?>" height="50" width="100" Alt="No image" />
          </td>
          <td>
               <img src="<?php echo $final_path_four; ?>" height="50" width="100" Alt="No image" />
          </td>
          <td><?php echo $item->getData('created_at'); ?></td>
           <td><a href="<?php echo $block->getUrl('addproductlogo/index/edit').'id/'.$item->getData('post_id'); ?>" class="action primary">Edit</a></td>
          <td><a href="<?php echo $block->getUrl('addproductlogo/index/delete').'?id='.$item->getData('post_id'); ?>" class="action primary" onclick="return confirm('Are you sure you want to delete All Logo?')">Delete</a></td>
     </tr>
     <?php } ?>
</table>