<a href="https://beta.pinksky.co.in/addproductlogo/index/display/">Product Logo list</a>
<table>
<form method="post" action="<?php echo $block->getUrl('addproductlogo/index/save'); ?>" enctype="multipart/form-data">
        <input type="file" name="logo">
        <input type="file" name="logo_one">
        <input type="file" name="logo_two">
        <input type="file" name="logo_three">
        <input type="file" name="logo_four">
        <input type="submit" name="submit">
    </form>
</table>
