<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpHyperLocal
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
 -->
<div class="pp-buttons-container">
    <input id="autocomplete" type="text" name="groups[general_settings][fields][address][value]" class="validate-no-html-tags input-text admin__control-text"/>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "autofilladdress": {
                "googleApiKey":"<?= $block->getHelper()->getGoogleApiKey() ?>",
                "savedAddress":"<?= $block->getHelper()->getAdminAddress() ?>"
            }
        }
    }
</script>