<?php

/**
 * @author     Apex Division <apexdivision@gmail.com>
 * @copyright  2019  Apex Division (https://apexdivision.com)
 * @license     Commercial
 */

namespace ApexDivision\ProductAttribute\Setup;

use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallData implements InstallDataInterface {

    /**
     * Eav setup factory
     * @var EavSetupFactory
     */
    private $eavSetupFactory;

    /**
     * Init
     * @param EavSetupFactory $eavSetupFactory
     */
    public function __construct(\Magento\Eav\Setup\EavSetupFactory $eavSetupFactory) {
        $this->eavSetupFactory = $eavSetupFactory;
    }

    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     */
    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context) {
        $eavSetup = $this->eavSetupFactory->create();
        
        $attributesInfo = [
            'tjuk_badge_4_toggle' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Badge 4 Toggle',
                'input' => 'boolean',
                'default_value_yesno' => 0,
                'required' => false,
                'user_defined' => true,
                'sort_order' => 50,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'comparable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'visible_in_advanced_search' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_badge_5_toggle' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Badge 5 Toggle',
                'input' => 'boolean',
                'default_value_yesno' => 0,
                'required' => false,
                'user_defined' => true,
                'sort_order' => 51,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'comparable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'visible_in_advanced_search' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_hsn_code' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'HSN Code',
                'input' => 'text',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 52,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => true,
                'visible_on_front' => true,
                'searchable' => true,
                'filterable' => false,
                'search_weight' => 1,
                'visible_in_advanced_search' => true,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => 0,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_custom_block_1' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Custom Block 1',
                'input' => 'texteditor',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 53,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'filterable' => false,
                'visible_in_advanced_search' => false,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => true,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => true,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_custom_block_2' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Custom Block 2',
                'input' => 'texteditor',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 54,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'filterable' => false,
                'visible_in_advanced_search' => false,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => true,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => true,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_display_unit' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Display Unit',
                'input' => 'text',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 55,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => false,
                'visible_on_front' => true,
                'searchable' => false,
                'filterable' => false,
                'visible_in_advanced_search' => false,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => false,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_display_unit_type' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Display Unit Type',
                'input' => 'text',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 56,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => false,
                'visible_on_front' => true,
                'searchable' => false,
                'filterable' => false,
                'visible_in_advanced_search' => false,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => false,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_ingredients' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Ingredients',
                'input' => 'textarea',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 57,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => true,
                'visible_on_front' => true,
                'searchable' => true,
                'filterable' => false,
                'visible_in_advanced_search' => true,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => true,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => true,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_lot_no' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Lot No.',
                'input' => 'text',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 58,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => false,
                'visible_on_front' => true,
                'searchable' => true,
                'filterable' => false,
                'visible_in_advanced_search' => true,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => true,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_manufacturing_date' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Manufacturing Date',
                'input' => 'text',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 59,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => false,
                'visible_on_front' => true,
                'searchable' => false,
                'filterable' => false,
                'visible_in_advanced_search' => false,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_moq' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'MOQ',
                'input' => 'text',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 60,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'is_html_allowed_on_front' => false,
                'visible_on_front' => true,
                'searchable' => false,
                'filterable' => false,
                'visible_in_advanced_search' => false,
                'comparable' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_natural_toggle' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Natural Toggle',
                'input' => 'boolean',
                'default_value_yesno' => 0,
                'required' => false,
                'user_defined' => true,
                'sort_order' => 61,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'comparable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'visible_in_advanced_search' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_organic_toggle' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Organic Toggle',
                'input' => 'boolean',
                'default_value_yesno' => 0,
                'required' => false,
                'user_defined' => true,
                'sort_order' => 62,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'comparable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'visible_in_advanced_search' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_preservative_free_toggle' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Preservative Free Toggle',
                'input' => 'boolean',
                'default_value_yesno' => 0,
                'required' => false,
                'user_defined' => true,
                'sort_order' => 63,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'comparable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'visible_in_advanced_search' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_shelf_life_total' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Shelf Life (Total)',
                'input' => 'text',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 64,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'comparable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'visible_in_advanced_search' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
            'tjuk_standard_selling_price_individual_unit' => [
                'group' => 'General',
                'type' => 'varchar',
                'label' => 'Standard Selling Price Individual Unit',
                'input' => 'price',
                'required' => false,
                'user_defined' => true,
                'sort_order' => 64,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'unique' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'visible' => true,
                'visible_on_front' => true,
                'searchable' => false,
                'comparable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'visible_in_advanced_search' => false,
                'position' => 0,
                'wysiwyg_enabled' => false,
                'used_for_promo_rules' => false,
                'is_html_allowed_on_front' => false,
                'is_visible_on_front' => true,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false
            ],
        ];
        
        
        foreach ($attributesInfo as $attributeCode => $attributeParams) {
            $eavSetup->addAttribute(\Magento\Catalog\Model\Product::ENTITY, $attributeCode, $attributeParams);
        }
        
        
//        $eavSetup->addAttribute(
//                \Magento\Catalog\Model\Product::ENTITY,
//                'tjuk_hsn_code',
//                [
//                    'group' => 'General',
//                    'type' => 'varchar',
//                    'label' => 'HSN Code',
//                    'input' => 'text',
//                    'required' => false,
//                    'user_defined' => true,
//                    'sort_order' => 50,
//                    'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
//                    'unique' => false,
//                    'is_used_in_grid' => true,
//                    'is_visible_in_grid' => true,
//                    'is_filterable_in_grid' => true,
//                    'visible' => true,
//                    'is_html_allowed_on_front' => true,
//                    'visible_on_front' => true,
//                    'searchable' => true,
//                    'filterable' => true,
//                    'search_weight' => 1,
//                    'visible_in_advanced_search' => true,
//                    'comparable' => false,
//                    'position' => 0,
//                    'wysiwyg_enabled' => 0,
//                    'used_for_promo_rules' => false,
//                    'is_html_allowed_on_front' => false,
//                    'is_visible_on_front' => true,
//                    'used_in_product_listing' => false,
//                    'used_for_sort_by' => false,
//                    'frontend_label' => array(0 => 'HSN Code', 1 => 'HSN Code')
//                ]
//        );
    }

}
