<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpHyperLocal
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
// @codingStandardsIgnoreFile

$helper = $this->helper('Webkul\Marketplace\Helper\Data');

$shipRateList = $block->getAllShipRate();
?>	
<div class="wk-mp-design">
	
		<form action="<?php echo $block->getSaveAction()?>" method="POST" id="form-customer-attr-new" data-mage-init='{"validation":{}}' enctype="multipart/form-data">
		<fieldset class="info wk-mp-fieldset fieldset" id="shipping-rate">
			<legend class="legend">
				<span><?php echo __('Add your shipping rate')?></span>
				<a href="<?php echo $block->getViewFileUrl('Webkul_MpHyperLocal::hyper-local-shiprate.csv')?>"><?php echo __('Download Sample File')?></a>
				<button class="button wk-mp-btn" title="Save" type="submit" id="save-btn">
					<span><span><?php echo __('Save')?></span></span>
				</button>
			</legend>			
			<?php echo $block->getBlockHtml('formkey'); ?>
			<?php echo $block->getBlockHtml('seller.formkey'); ?>
			<div class="fieldset form-list" id="cust">
				<div class="field required">
					<label class="label"><?php echo __('Upload CSV ')?></label>
					<div class="control">
						<input class="input-text required-entry" name="rate-csv-file" id="rate-csv-file" type="file" />
					</div>
				</div>
			</div>
			</fieldset>
		</form>
	
	<fieldset class="fieldset info wk-mp-fieldset">
		<legend class="legend">
			<span><?php /* @escapeNotVerified */ echo __('My Ship Rate List') ?></span>
		</legend>
		<div class="grid">
			<div class="hor-scroll">
				<?php if ($shipRateList && count($shipRateList)): ?>
					<form action="<?php echo $block->getUrl('mphyperlocal/account/massdeleterate', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-ratelist-massdelete" name="formProductlistMassDisable" data-mage-init='{"validation":{}}'>
						<?php echo $block->getBlockHtml('formkey')?>
						<?php echo $block->getBlockHtml('seller.formkey')?>
						<button class="button" title="<?php /* @escapeNotVerified */ echo __('Delete Ship Rate') ?>" type="submit" id="mass-delete-butn">
							<span>
								<span><?php /* @escapeNotVerified */ echo __('Delete Ship Rate') ?></span>
							</span>
						</button>
						<table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
						    <thead>
						        <tr class="wk-content">
						        	<th class="wk-check-first-td">
						    			<span>
											<input type="checkbox" name="mpselecctall" value="all" id="mp-hyper-local-allcheck"/>
										</span>
						    		</th>
						    		<th class="wk-first-td name">
						    			<span class="label"><?php /* @escapeNotVerified */ echo __('Distance')?></span>
						    		</th>
						    		<th class="wk-first-td">
						    			<span class="label"><?php /* @escapeNotVerified */ echo __('Weight')?></span>
						    		</th>
						    		<th class="wk-first-td">
						    			<span class="label name"><?php /* @escapeNotVerified */ echo __('Cost')?></span>
						    		</th>
						    		<th>
						    			<span class="label"><?php /* @escapeNotVerified */ echo __('Action')?></span>
						    		</th>			    		
						    	</tr>
						    </thead>
						    <tbody>
						    	<?php 
						    	$i = 0;
								foreach($shipRateList as $shipRate){
									$i++;
									?>
							    	<tr class="wk-row-view <?php /* @escapeNotVerified */ echo $class = ($i == count($shipRateList))? 'wk-last_tr':''?>">
							    		<td class="wk-check-first-td">
							    			<span>
												<input type="checkbox" name="ship_rate_mass_delete[]" class="mpcheckbox" value="<?php /* @escapeNotVerified */ echo $shipRate->getEntityId(); ?>"/>
											</span>
							    		</td>
							    		<td class="wk-first_td">
							    			<div>
							    				<span><?php echo __('From :')?></span>
							    				<?php echo $shipRate->getDistanceFrom()?>
							    			</div>
							    			<div>
							    				<span><?php echo __('To :')?></span>
							    				<?php echo $shipRate->getDistanceTo()?>
							    			</div>
							    		</td>
							    		<td class="wk-first_td">
							    			<div>
							    				<span><?php echo __('From :')?></span>
							    				<?php echo $shipRate->getWeightFrom()?>
							    			</div>
							    			<div>
							    				<span><?php echo __('To :')?></span>
							    				<?php echo $shipRate->getWeightTo()?>
							    			</div>
							    		</td>
							    		<td><span><?php echo $block->getFormatedPrice($shipRate->getCost())?></span></td>
							    		<td>
						    				<a href="<?php /* @escapeNotVerified */ echo $block->getDeleteUrl($shipRate->getEntityId())?>" class="button delete" ><?php /* @escapeNotVerified */ echo __('Delete') ?></a>
							    		</td>			    		
							    	</tr>
							    	<?php
							    }?>
						    </tbody>
						</table>
					</form>				
				<?php else: ?>
					<div class="wk-emptymsg">
						<?php /* @escapeNotVerified */ echo __('No ship rate available') ?>
					</div>
				<?php endif ?>					
			</div>
		</div>
		<?php if ($block->getPagerHtml()): ?>
	        <div class="order-products-toolbar toolbar bottom"><?php /* @escapeNotVerified */ echo $block->getPagerHtml(); ?></div>
	    <?php endif ?>	
	</fieldset>	
	<div class="buttons-set">
		<p class="back-link">
			<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php /* @escapeNotVerified */ echo __('Back') ?></a>
		</p>
	</div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "masssellectactions": {}
        }
    }
</script>