<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpHyperLocal
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$shipAreaList = $block->getAllShipArea();
?>    
<div class="wk-mp-design">
    <form action="<?= $block->getSaveAction()?>" method="POST" id="form-customer-attr-new" data-mage-init='{"validation":{}}'>
        <fieldset class="info wk-mp-fieldset fieldset" id="associate-product">
            <legend class="legend">
                <span><?= __('Add your ship area')?></span>
                <button class="button wk-mp-btn" title="Save" type="submit" id="save-btn">
                    <span><span><?= __('Save')?></span></span>
                </button>
            </legend>            
            <?= $block->getBlockHtml('formkey'); ?>
            <?= $block->getBlockHtml('seller.formkey'); ?>
            <div class="fieldset form-list" id="cust">
                <div class="field required">
                    <label class="label"><?= __('Enter Location')?></label>
                    <div class="control">
                        <input class="input-text required-entry" name="address" id="autocompleteform" type="text" />
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= __('Address Type')?></label>
                    <div class="control">
                        <select class="required-entry" name="address_type" id="address_type">
                            <option value=""><?= __('--select--'); ?></option>
                            <option value="city"><?= __('City'); ?></option>
                            <option value="state"><?= __('State'); ?></option>
                            <option value="country"><?= __('Country'); ?></option>
                        </select>
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= __('Latitude')?></label>
                    <div class="control">
                        <input class="required-entry input-text" readonly="readonly" name="latitude" id="latitude" type="text" />
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= __('Longitude')?></label>
                    <div class="control">
                        <input class="required-entry input-text" readonly="readonly" name="longitude" id="longitude" type="text" />
                    </div>
                </div>
            </div>
            </fieldset>
        </form>
    
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?= /* @escapeNotVerified */ __('My Ship Area List') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <?php if ($shipAreaList && count($shipAreaList)): ?>
                    <form action="<?= $block->getUrl('mphyperlocal/account/massdeletearea', ['_secure' => $block->getRequest()->isSecure()]) ?>" method="post" id="form-arealist-massdelete" name="formProductlistMassDisable" data-mage-init='{"validation":{}}'>
                        <?= $block->getBlockHtml('formkey')?>
                        <?= $block->getBlockHtml('seller.formkey'); ?>
                        <button class="button" title="<?= /* @escapeNotVerified */ __('Delete Ship Area') ?>" type="submit" id="mass-delete-butn">
                            <span>
                                <span><?= /* @escapeNotVerified */ __('Delete Ship Area') ?></span>
                            </span>
                        </button>
                        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mp-hyper-local-allcheck"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td name">
                                        <span class="label"><?= /* @escapeNotVerified */ __('Address')?></span>
                                    </th>
                                    <th class="wk-first-td name">
                                        <span class="label"><?= /* @escapeNotVerified */ __('Address Type')?></span>
                                    </th>
                                    <th class="wk-first-td qty">
                                        <span class="label"><?= /* @escapeNotVerified */ __('Latitude')?></span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name"><?= /* @escapeNotVerified */ __('Longitude')?></span>
                                    </th>
                                    <th>
                                        <span class="label"><?= /* @escapeNotVerified */ __('Action')?></span>
                                    </th>                        
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;
                                foreach ($shipAreaList as $shipArea) {
                                    $i++;
                                    ?>
                                    <tr class="wk-row-view <?= /* @escapeNotVerified */ $class = ($i == count($shipAreaList))? 'wk-last_tr':''?>">
                                        <td class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="ship_area_mass_delete[]" class="mpcheckbox" value="<?= /* @escapeNotVerified */ $shipArea->getEntityId(); ?>"/>
                                            </span>
                                        </td>
                                        <td class="wk-first_td"><?= $shipArea->getAddress()?></td>
                                        <td class="wk-first_td"><?= $shipArea->getAddressType()?></td>
                                        <td><?= $shipArea->getLatitude()?></td>
                                        <td><span><?= $shipArea->getLongitude()?></span></td>
                                        <td>
                                            <a href="<?= /* @escapeNotVerified */ $block->getDeleteUrl($shipArea->getEntityId())?>" class="button delete" ><?= /* @escapeNotVerified */ __('Delete') ?></a>
                                        </td>                        
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                    </form>                
                <?php else: ?>
                    <div class="wk-emptymsg">
                        <?= /* @escapeNotVerified */ __('No ship area available') ?>
                    </div>
                <?php endif ?>                    
            </div>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= /* @escapeNotVerified */ $block->getPagerHtml(); ?></div>
        <?php endif ?>    
    </fieldset>    
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?= /* @escapeNotVerified */ __('Back') ?></a>
        </p>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "masssellectactions": {
                "googleApiKey":"<?= $block->getHelper()->getGoogleApiKey()?>"
            }
        }
    }
</script>