<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpHyperLocal
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$seller = $block->getOrigin();
if ($seller->getIsSeller()) {
    $unit = $block->getHelper()->getRadiusUnitValue();
    ?>    
<div class="wk-mp-design">
        <form action="<?= $block->getSaveAction()?>" method="POST" id="form-customer-attr-new" data-mage-init='{"validation":{}}'>
            <fieldset class="info wk-mp-fieldset fieldset" id="associate-product">
            <legend class="legend">
                <span><?= __('Add your shipping origin address')?></span>
                <button class="button wk-mp-btn" title="Save" type="submit" id="save-btn">
                    <span><span><?= __('Save')?></span></span>
                </button>
            </legend>            
            <?= $block->getBlockHtml('formkey'); ?>
            <?= $block->getBlockHtml('seller.formkey'); ?>
            <div class="fieldset form-list" id="cust">
                <div class="field required">
                    <label class="label"><?= __('Enter Location')?></label>
                    <div class="control">
                        <input class="input-text required-entry" value="<?= $seller->getOriginAddress()?>" name="origin_address" id="autocompleteform" type="text" />
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= __('Latitude')?></label>
                    <div class="control">
                        <input class="required-entry input-text" value="<?= $seller->getLatitude()?>" readonly="readonly" name="latitude" id="latitude" type="text" />
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= __('Longitude')?></label>
                    <div class="control">
                        <input class="required-entry input-text" value="<?= $seller->getLongitude()?>" readonly="readonly" name="longitude" id="longitude" type="text" />
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= __('Radius '.'('.$unit.')')?></label>
                    <div class="control">
                        <input class="required-entry validate-number input-text" value="<?= $seller->getRadius()?>" name="radius" id="radius" type="text" />
                    </div>
                </div>
            </div>
            </fieldset>
        </form>
    
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?= /* @escapeNotVerified */ __('Back') ?></a>
        </p>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "masssellectactions": {
                "googleApiKey":"<?= $block->getHelper()->getGoogleApiKey()?>"
            }
        }
    }
</script>
<?php } ?>
