<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$partner=$block->getProfileDetail();
if ($partner['shop_url']) {
    if ($helper->getActiveColorPicker()) { ?>
        <style>
            .page-main{
                background-image:none;
                background-color:<?= $block->escapeHtml($partner['background_width']);?>;
            } 
        </style>
    <?php } ?>
    <div class="seller-profile inner">
        <h3 class="h3"><?= $block->escapeHtml(__("About Me"))?></h3>
        <p><?= /* @noEscape */ $partner['company_description'];?></p>
        <p><?= $block->getChildHtml("marketplace_seller_description")?></p>

        <?php if ($helper->getSellerPolicyApproval()) { ?>
                <br><br>
            <h3 class="h3"><?= $block->escapeHtml(__("Shipping Policy"))?></h3>
            <p><?= /* @noEscape */ $partner['shipping_policy'];?></p>
            <br><br>
            <h3 class="h3"><?= /* @noEscape */ __("Return Policy")?></h3>
            <p><?= /* @noEscape */ $partner['return_policy'];?></p>
        <?php } ?>
    </div>
    <div class="row-am category">
        <?= $block->getChildHtml("marketplace_seller_top_block")?>
        <div class="wk-mp-collection-container">
            <?= $this->getChildHtml('marketplace_sellerprofile_recently_added_products')?>
        </div>
    </div>
<?php }  ?>
