<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button type="button" data-role="all-tocart" title="<?php echo __('Add All to Bag') ?>" class="action tocart primary">
        <span><?php echo __('Add All to Bag') ?></span>
    </button>
<?php endif;?>
