<?php

use Webkul\Grid\Block\Index;

?>

<h2 style="text-align: center;">Categories</h2>

<a class="action primary" style="margin-left: 85%;" href="<?php echo $block->getUrl('grid/index/insert'); ?>">Add Category</a>

<table>
     <tr>
          <th>Id</th>
          <th>Title</th>
          <th>Content</th>
          <th>URL</th>
          <th>Image</th>
          <th>Created At</th>
          <!-- <th>Updated At</th> -->
          <th colspan="2">Action</th>
     </tr>
 
     <?php
          
          $collection = $block->getResult();
          foreach($collection as $item){
          	$image = $item->getData('image');
     		$image_path = $block->getUrl("pub/media/images/");
     		$final_path = $image_path.$image;
     ?>
     <tr>
          <td><?php echo $item->getData('entity_id'); ?></td>
          <td><?php echo $item->getData('title'); ?></td>
          <td><?php echo $item->getData('content'); ?></td>
          <td><?php echo $item->getData('url'); ?></td>
          <td>
          	<img src="<?php echo $final_path; ?>" height="50" width="100" Alt="No image" /></td>
          <td><?php echo $item->getData('created_at'); ?></td>
          <!-- <td><?php echo $item->getData('publish_date'); ?></td> -->
          <td><a href="<?php echo $block->getUrl('grid/index/edit').'id/'.$item->getData('entity_id'); ?>" class="action primary">Edit</a></td>
          <td><a href="<?php echo $block->getUrl('grid/index/delete').'?id='.$item->getData('entity_id'); ?>" class="action primary" onclick="return confirm('Are you sure you want to delete this category?')">Delete</a></td>
     </tr>
     <?php } ?>
</table>