<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpHyperLocal
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$shipAreaList = $block->getAllShipArea();
?>	
<div class="wk-mp-design">
	
		<form action="<?php echo $block->getSaveAction()?>" method="POST" id="form-customer-attr-new" data-mage-init='{"validation":{}}'>
		<fieldset class="info wk-mp-fieldset fieldset" id="associate-product">
			<legend class="legend">
				<span><?php echo __('Add your ship area')?></span>
				<button class="button wk-mp-btn" title="Save" type="submit" id="save-btn">
					<span><span><?php echo __('Save')?></span></span>
				</button>
			</legend>			
			<?php echo $block->getBlockHtml('formkey'); ?>
			<?php echo $block->getBlockHtml('seller.formkey'); ?>
			<div class="fieldset form-list" id="cust">
				<div class="field required">
					<label class="label"><?php echo __('Enter Location')?></label>
					<div class="control">
						<input class="input-text required-entry" name="address" id="autocompleteform" type="text" />
					</div>
				</div>
				<div class="field required">
					<label class="label"><?php echo __('Address Type')?></label>
					<div class="control">
						<select class="required-entry" name="address_type" id="address_type">
							<option value=""><?php echo __('--select--'); ?></option>
							<option value="city"><?php echo __('City'); ?></option>
							<option value="state"><?php echo __('State'); ?></option>
							<option value="country"><?php echo __('Country'); ?></option>
						</select>
					</div>
				</div>
				<div class="field required">
					<label class="label"><?php echo __('Latitude')?></label>
					<div class="control">
						<input class="required-entry input-text" readonly="readonly" name="latitude" id="latitude" type="text" />
					</div>
				</div>
				<div class="field required">
					<label class="label"><?php echo __('Longitude')?></label>
					<div class="control">
						<input class="required-entry input-text" readonly="readonly" name="longitude" id="longitude" type="text" />
					</div>
				</div>
			</div>
			</fieldset>
		</form>
	
	<fieldset class="fieldset info wk-mp-fieldset">
		<legend class="legend">
			<span><?php /* @escapeNotVerified */ echo __('My Ship Area List') ?></span>
		</legend>
		<div class="grid">
			<div class="hor-scroll">
				<?php if ($shipAreaList && count($shipAreaList)): ?>
					<form action="<?php echo $block->getUrl('mphyperlocal/account/massdeletearea', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-arealist-massdelete" name="formProductlistMassDisable" data-mage-init='{"validation":{}}'>
						<?php echo $block->getBlockHtml('formkey')?>
						<?php echo $block->getBlockHtml('seller.formkey'); ?>
						<button class="button" title="<?php /* @escapeNotVerified */ echo __('Delete Ship Area') ?>" type="submit" id="mass-delete-butn">
							<span>
								<span><?php /* @escapeNotVerified */ echo __('Delete Ship Area') ?></span>
							</span>
						</button>
						<table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
						    <thead>
						        <tr class="wk-content">
						        	<th class="wk-check-first-td">
						    			<span>
											<input type="checkbox" name="mpselecctall" value="all" id="mp-hyper-local-allcheck"/>
										</span>
						    		</th>
						    		<th class="wk-first-td name">
						    			<span class="label"><?php /* @escapeNotVerified */ echo __('Address')?></span>
						    		</th>
						    		<th class="wk-first-td name">
						    			<span class="label"><?php /* @escapeNotVerified */ echo __('Address Type')?></span>
						    		</th>
						    		<th class="wk-first-td qty">
						    			<span class="label"><?php /* @escapeNotVerified */ echo __('Latitude')?></span>
						    		</th>
						    		<th class="wk-first-td">
						    			<span class="label name"><?php /* @escapeNotVerified */ echo __('Longitude')?></span>
						    		</th>
						    		<th>
						    			<span class="label"><?php /* @escapeNotVerified */ echo __('Action')?></span>
						    		</th>			    		
						    	</tr>
						    </thead>
						    <tbody>
						    	<?php 
						    	$i = 0;
								foreach($shipAreaList as $shipArea){
									$i++;
									?>
							    	<tr class="wk-row-view <?php /* @escapeNotVerified */ echo $class = ($i == count($shipAreaList))? 'wk-last_tr':''?>">
							    		<td class="wk-check-first-td">
							    			<span>
												<input type="checkbox" name="ship_area_mass_delete[]" class="mpcheckbox" value="<?php /* @escapeNotVerified */ echo $shipArea->getEntityId(); ?>"/>
											</span>
							    		</td>
							    		<td class="wk-first_td"><?php echo $shipArea->getAddress()?></td>
							    		<td class="wk-first_td"><?php echo $shipArea->getAddressType()?></td>
							    		<td><?php echo $shipArea->getLatitude()?></td>
							    		<td><span><?php echo $shipArea->getLongitude()?></span></td>
							    		<td>
						    				<a href="<?php /* @escapeNotVerified */ echo $block->getDeleteUrl($shipArea->getEntityId())?>" class="button delete" ><?php /* @escapeNotVerified */ echo __('Delete') ?></a>
							    		</td>			    		
							    	</tr>
							    	<?php
							    }?>
						    </tbody>
						</table>
					</form>				
				<?php else: ?>
					<div class="wk-emptymsg">
						<?php /* @escapeNotVerified */ echo __('No ship area available') ?>
					</div>
				<?php endif ?>					
			</div>
		</div>
		<?php if ($block->getPagerHtml()): ?>
	        <div class="order-products-toolbar toolbar bottom"><?php /* @escapeNotVerified */ echo $block->getPagerHtml(); ?></div>
	    <?php endif ?>	
	</fieldset>	
	<div class="buttons-set">
		<p class="back-link">
			<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php /* @escapeNotVerified */ echo __('Back') ?></a>
		</p>
	</div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "masssellectactions": {
    			"googleApiKey":"<?php echo $block->getHelper()->getGoogleApiKey()?>"
            }
        }
    }
</script>