<!-- <?php $_product = $block->getProduct();
?>
<div class="social-media-icons">
    <h5>Share on :</h5> -->
    <!-- WhatsApp -->
    <!-- <a target="_blank" href="https://api.whatsapp.com/send?text=<?php echo urlencode($_product->getProductUrl());?>">
            <img src="<?php echo $this->getBaseUrl().'pub/media/logo/stores/1/whatsapp.png'; ?>" alt="Whatsapp" width="8%"></a> -->
    
    <!-- Facebook -->
    
    <!-- <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on facebook">
        <img src="<?php echo $this->getBaseUrl().'pub/media/logo/stores/1/facebook-share.png'; ?>" alt="Facebook" width="8%">
    </a> -->

    <!-- TWITTER -->

    <!-- <a href="http://twitter.com/home/?status=<?php echo urlencode($_product->getProductUrl());?>(<?php echo urlencode($_product->getName())?>)" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on Twitter">
        <img src="<?php echo $this->getBaseUrl().'pub/media/logo/stores/1/tw.png'; ?>" alt="Twitter" width="8%">
    </a> -->

   <!--  <a href="https://www.instagram.com?u=<?php echo urlencode($_product->getProductUrl());?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on Instagram">
        <img src="<?php echo $this->getBaseUrl().'pub/media/logo/stores/1/instagram.png'; ?>" alt="Instagram" width="8%">
    </a> -->

    <!-- Pinterest -->
<!-- </div> -->