<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpHyperLocal
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $block->getHelper();
$address = $helper->getSavedAddress();
?>
<li>
<span id="selected-location"><?php echo $address ? $address['address'] :''; ?></span>
<i class="material-icons my_location">my_location</i>
</li>
<div class="wk-mp-design select-address-popup-parent" style="display: none;">
    <fieldset class="info wk-mp-fieldset fieldset" id="select-address-popup">
        <div class="fieldset form-list" id="cust">
            <div class="field">
                <label class="label"><?php echo __('Enter Location')?></label>
                <div class="control">
                    <input class="input-text" data-lat="<?php echo $address ? $address['latitude'] :'' ?>" data-lng="<?php echo $address ? $address['longitude']:''?>" data-city="<?php echo $address ? $address['city'] :'' ?>" data-state="<?php echo $address ? $address['state'] :'' ?>" data-country="<?php echo $address ? $address['country'] :'' ?>" name="address" value="<?php echo $address ? $address['address'] :''?>" id="autocomplete" type="text" />
                </div>
            </div>
        </div>
    </fieldset> 
</div>
<script>
require.config({
    map: {
        '*': {
            'googleMapPlaceLibrary': 'https://maps.googleapis.com/maps/api/js?key=<?php echo $helper->getGoogleApiKey()?>&v=3.exp&libraries=places'
        }
    }
 });
 </script>
<script type="text/x-magento-init">
    {
        "*": {
            "addresspopup": {
                "saveAction": "<?php echo $block->getSaveAction()?>",
                "isAddressSet": "<?php echo $address ? 1:0 ?>",
                "popupHeading": "<?php echo $helper->getPopupMessage()?>"
            }
        }
    }
</script>