<?php
$blockObj= $block->getLayout()->createBlock(\Webkul\MpHyperLocal\Block\AddressForm::class);
$helper = $blockObj->getHelper();
$address = $helper->getSavedAddress();
?>

<div style="float:right;">
    <div class="field" style="border: 1px solid #ccc; display:inline-block; margin-right:5px;">
        <div style="display:inline-block;vertical-align: middle; text-align:center;">
            <i class="material-icons location_on">location_on</i>
        </div>
        <div class="control" style="width:200px; display:inline-block;">
            <input class="input-text" data-lat="<?= $address ? $address['latitude'] :'' ?>" data-lng="<?= $address ? $address['longitude']:''?>" data-city="<?= $address ? $address['city'] :'' ?>" data-state="<?= $address ? $address['state'] :'' ?>" data-country="<?= $address ? $address['country'] :'' ?>" name="address" value="<?= $address ? $address['address'] :''?>" id="autocomplete" type="text" placeholder="<?= $helper->getPopupMessage() ?>" style="border:none;"/>
        </div>
    </div>
</div>
<div class="wk-mp-design" style="display: none;">
    <fieldset class="info wk-mp-fieldset fieldset" id="select-address-popup">
        <div class="fieldset form-list" id="cust">
            <div class="field">
                <label class="label"><?= __('Enter Location')?></label>
                <div class="control">
                    <input class="input-text" data-lat="<?= $address ? $address['latitude'] :'' ?>" data-lng="<?= $address ? $address['longitude']:''?>" data-city="<?= $address ? $address['city'] :'' ?>" data-state="<?= $address ? $address['state'] :'' ?>" data-country="<?= $address ? $address['country'] :'' ?>" name="address" value="<?= $address ? $address['address'] :''?>" id="wkautocomplete" type="text" />
                </div>
            </div>
        </div>
    </fieldset> 
</div>

<script>
require.config({
    map: {
        '*': {
            'googleMapPlaceLibrary': 'https://maps.googleapis.com/maps/api/js?key=<?= $helper->getGoogleApiKey()?>&v=3.exp&libraries=places'
        }
    }
 });
 </script>
<script type="text/x-magento-init">
    {
        "*": {
            "addresspopup": {
                "saveAction": "<?= $blockObj->getSaveAction()?>",
                "getAction": "<?= $blockObj->getAddressAction()?>",
                "isAddressSet": "<?= $address ? 1:0 ?>",
                "popupHeading": "<?= $helper->getPopupMessage()?>"
            }
        }
    }
</script>