<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpHyperLocal
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $block->getHelper();
$address = $helper->getSavedAddress();
?>
<span id="selected-location"><?= $address ? $address['address'] :''; ?></span>
<i class="material-icons my_location">my_location</i>
<div class="wk-mp-design" style="display: none;">
    <fieldset class="info wk-mp-fieldset fieldset" id="select-address-popup">
        <div class="fieldset form-list" id="cust">
            <div class="field">
                <label class="label"><?= __('Enter Location')?></label>
                <div class="control">
                    <input class="input-text" data-lat="<?= $address ? $address['latitude'] :'' ?>" data-lng="<?= $address ? $address['longitude']:''?>" data-city="<?= $address ? $address['city'] :'' ?>" data-state="<?= $address ? $address['state'] :'' ?>" data-country="<?= $address ? $address['country'] :'' ?>" name="address" value="<?= $address ? $address['address'] :''?>" id="autocomplete" type="text" />
                </div>
            </div>
        </div>
    </fieldset> 
</div>
<script>
require.config({
    map: {
        '*': {
            'googleMapPlaceLibrary': 'https://maps.googleapis.com/maps/api/js?key=<?= $helper->getGoogleApiKey()?>&v=3.exp&libraries=places'
        }
    }
 });
 </script>
<script type="text/x-magento-init">
    {
        "*": {
            "addresspopup": {
                "saveAction": "<?= $block->getSaveAction()?>",
                "getAction": "<?= $blockObj->getAddressAction()?>",
                "isAddressSet": "<?= $address ? 1:0 ?>",
                "popupHeading": "<?= $helper->getPopupMessage()?>"
            }
        }
    }
</script>