<?php if ($block->isEnabled()): 
$helper         = $this->helper('Lof\SocialLogin\Helper\Data');
$lg_column_item = $helper->getConfigValue('sociallogin/general/lg_column_item');
$md_column_item = $helper->getConfigValue('sociallogin/general/md_column_item');
$sm_column_item = $helper->getConfigValue('sociallogin/general/sm_column_item'); 
$xs_column_item = $helper->getConfigValue('sociallogin/general/xs_column_item'); 

$popup_width    = $helper->getConfigValue('sociallogin/facebook/popup_width'); 
$popup_height   = $helper->getConfigValue('sociallogin/facebook/popup_height');

$popup_width    = $popup_width ? $popup_width : 800;
$popup_height   = $popup_height ? $popup_height : 600;

$lg_column      = 12/$lg_column_item;
$md_column      = 12/$md_column_item;
$sm_column      = 12/$sm_column_item; 
$xs_column      = 12/$xs_column_item; 

$title = $helper->getConfigValue('sociallogin/facebook/title_social');
$col = 'col-lg-'.$lg_column.' col-md-'.$md_column.' col-sm-'.$sm_column.' col-xs-'.$xs_column.'';
?>
    <div class="actions-toolbar social-btn facebook-login <?php echo $col;?>">
        <div class="primary">
            <button class="action btn_facebook_login" type="button">
                <span>
                    <span><i class="fa fa-facebook icon-social" aria-hidden="true" ></i><?php echo $title; ?></span>
                </span>
            </button>
        </div>
    </div>

    <script>
        require(['jquery', 'lof/sociallogin'], function ($, SocialLoginPopup) {
            $('.btn_facebook_login').click(function(e) {
                var popup_width  = <?php echo (isset($popup_width) && $popup_width)?(int)$popup_width:''; ?>;
                var popup_height = <?php echo (isset($popup_height) && $popup_height)?(int)$popup_height:''; ?>; 
                var fbPopup = new SocialLoginPopup(popup_width, popup_height);
                fbPopup.openPopup('<?php echo $block->getLoginUrl()?>', '<?php echo __('Login By Facebook')?>');
            })
        });
    </script>
<?php endif; ?>